### ISSUE TITLE
'show_titles' should reflect the specified quantiles (?)

### ISSUE THREAD

**Issue by JamesSample** [dfm/corner.py#107]
Not sure whether this is a very minor issue or just me misunderstanding the intended behaviour...

If I specify `quantiles` in my call to `corner.corner()`, I get vertical lines on the histograms at my specified quantiles, but the plot titles always assume `quantiles=[0.16, 0.5, 0.84]` (see [here](https://github.com/dfm/corner.py/blob/master/corner/corner.py#L275)). 

Shouldn't `show_titles` use the specified quantiles? Perhaps something like this for lines 277 to 282:

    if title_fmt is not None:
        # Compute the quantiles for the title. This might redo
        # unneeded computation but who cares.
        q_l, q_50, q_u = quantile(x, quantiles, weights=weights)
        q_m, q_p = q_50-q_l, q_u-q_50

Thanks for an awesome package!

**Comment by dfm** [comment]
This is definitely a bug either with the docs or the code, but I think that it might be better to just fix the docstring to reflect the current behavior. Alternatively, there could be an error thrown if the user doesn't provide exactly 3 quantiles.

**Comment by JamesSample** [comment]
Thanks Dan. I guess it is useful to be able to plot more than three quantile lines if desired, so perhaps updating the docstring is the best way to go, as you suggest. Intervals for the specified quantiles can still be obtained by passing `verbose=True` if desired.

**Comment by benjaminrose** [comment]
Is this the same issue as #94?

**Comment by alessandropeca** [comment]
Any news?

**Comment by benjaminrose** [comment]
@alessandropeca, I am stills slowly working on #108, but it is not done yet. That is not exactly the same as this issue, but they are related. I can share the WIP code I have if you (or anyone) wishes.

**Comment by jhmatthews** [comment]
I've just come across this issue. This seems important to fix since it'd be quite easy to quote incorrect 90% confidence intervals, for example, particularly for quite steep posterior distributions. 

Unless #108 is nearly done @benjaminrose , I'd suggest a simpler fix where one additional kwarg is used (say, ```title_quantiles```) to manually set the quantiles use in the calculation of the +- errorbars. If ```None``` (default), then use quantiles as the title_quantiles. 

The old behaviour could be recovered by always passing ```title_quantiles=[0.16,0.5,0.84]```. Note this wouldn't be as flexible/powerful as the proposed fix #108 but IMO sufficient.

**Comment by jhmatthews** [comment]
The slight problem with the simple fix above is that quantiles can be any length, and title_quantiles must be lenth-3, so this must be checked. It also needs to deal with the scenario that ``len(quantiles) == 0```, and ```title_quantiles is None```, probably by defaulting to the 1 sigma quantiles.

**Comment by benjaminrose** [comment]
@jhmatthews #108 was half implemented, but then fell behind the main repo. The work I have might be a pain to merge. I would fix what needs to be fixed and not worry about the half working code I wrote.

**Comment by jhmatthews** [comment]
I've proposed a fairly simple fix for this under PR #193.
