### ISSUE TITLE
contourf_kwargs malfunctioning?

### ISSUE THREAD

**Issue by jtbuch** [dfm/corner.py#112]
Hi,

I'm using the latest build of corner.py along with matplotlib 2.0.2 to make some corner plots of marginalized posteriors. Everything works perfectly until I try to pass the alpha argument to contourf_kwargs, in which case I obtain this result: 
![contour](https://user-images.githubusercontent.com/29380821/38648093-7f1e2fee-3dbd-11e8-93fa-37d9d7cb0197.png)

It seems weirdly reminiscent of #70 , but I can't quite place my finger on why things go awry. 

Any help will be appreciated! 

Here's my code for reference:
`corner.hist2d(param1, param2,  label_kwargs=dict(fontsize=12), color='gold', plot_datapoints=False,    plot_density=False, fill_contours=True, smooth=True, contourf_kwargs= dict(alpha=0.4), levels=(0.68, 0.95))`

**Comment by dfm** [comment]
This must be happening because the `alpha` parameter overloads the alpha of the contour colors. The way that this all works internally is that the contour levels have the color given by the `color` argument and then alpha levels so that the outer contour isn't plotted. If you want the contour to have different `alpha`, you will probably have to edit this code: https://github.com/dfm/corner.py/blob/master/corner/corner.py#L548 There isn't an argument that will do what you want.

**Comment by jtbuch** [comment]
Thanks, Dan!

The idea is to overlay contours on top of each other, so ideally there should be some transparency for each level. Let me try to edit the code and I'll post here if I figure something out.

Cheers,
Jatan

**Comment by Cosmicstring** [comment]
Any update on this? I want to achieve the same result of having transparent fillings for the contours, but I am unable to implement it and I am getting the same issue as above. I tried changing the order of `contour` and `contourf` inside the `hist2d` but it didn't help. Also, setting the colors of the contours with transparent rgba value isn't the result I was hoping for. Please let me know if there are any updates here!

I'm using the newest version of corner.py and matplotlib 3.1.3

**Comment by ryanbegley96** [comment]
> Any update on this? I want to achieve the same result of having transparent fillings for the contours, but I am unable to implement it and I am getting the same issue as above. I tried changing the order of `contour` and `contourf` inside the `hist2d` but it didn't help. Also, setting the colors of the contours with transparent rgba value isn't the result I was hoping for. Please let me know if there are any updates here!
> 
> I'm using the newest version of corner.py and matplotlib 3.1.3

Putting this here incase it is useful for others. Passing alpha as a list within contourf_kwargs given to hist2d behaves as I was hoping it would;  e.g., for 2 levels I passed contourf_kwargs={'alpha':[0.0, 0.2, 0.5]}.
