### ISSUE TITLE
WARNING is raised even when setting is turned off. 

### ISSUE THREAD

**Issue by koaning** [dfm/corner.py#122]
When I specify that plot contours are not needed I still can get a warning that there's not enough points to make one. This seems a bit too verbose perhaps. 

![image](https://user-images.githubusercontent.com/1019791/55224701-61c91300-5211-11e9-8f10-ccb2152096d6.png)

I might have a go at a fix if I can get a confirmation that this change is appreciated.

**Comment by dfm** [comment]
Thanks for the offer! We fixed this a while ago (the GitHub master version should no longer have this problem) but it looks like I haven't pushed to PyPI yet. Try updating to the GitHub version for now and I'll try to remember to push a release soonish. Thanks again!

**Comment by koaning** [comment]
Cool. I'll close this for now then.
