### ISSUE TITLE
Different formats for each parameter

### ISSUE THREAD

**Issue by csnap001** [dfm/corner.py#129]
Hello,
I've just noticed that it is not possible to apply different formatting for the title of each plot (The mean plus and minus the "error"). For example, a fit data set for a three parameter fit may have values for each parameter at different magnitudes such as (1.32e-12, 4.5, 4009). The title of each of these plots is then forced to follow a single formatting and can produce results like (a0 = 0.00, a1 = 4.5, a2 = 4009). It would be nice to be able to feed a list of formats into the title_fmt argument of corner.corner to avoid this issue. (NOTE: I have explicitly left out the plus/minus portion as I believe that it would be cumbersome and difficult to read)
Thank you.

**Comment by tdejaeger** [comment]
Hi,

Did you find a solution to apply different formatting for the title of each plot?
I am trying to do the same...

Thank you very much!!

**Comment by csnap001** [comment]
@tdejaeger 
I spent some time digging into the code and found that it is currently designed to only use a single format. I accepted this at the time instead of trying to modify the source code and simply used "title_fmt = '.2E'" which works well enough for my purposes. You can try to modify the source code to allow for lists or arrays of titles (this is what I plan to do at some point), but this may be a cumbersome task. Sorry I couldn't be of more help, best of luck.

**Comment by tdejaeger** [comment]
Hi, I found a solution. I create a new keyword in the corner function: hist_title

def corner_new(xs, bins=20, range=None, weights=None, color="k", hist_bin_factor=1, smooth=None, smooth1d=None,labels=None,title_hist=None, label_kwargs=None,show_titles=False, title_fmt=".2f", title_kwargs=None,truths=None, truth_color="#4682b4",scale_hist=False, quantiles=None, verbose=False, fig=None,max_n_ticks=5, top_ticks=False, use_math_text=False, reverse=False,hist_kwargs=None, **hist2d_kwargs)

And I changed this line 264
title = "{0}".format(title_hist[i])

Then in my main program I have this:

tlabels = [r"$\alpha$",r"$\beta$",r"$\gamma$" ]
tlabels_final=[]
for p in range(shape(samples)[1]):
	q_16, q_50, q_84 = quantile(samples[:,p], [0.16, 0.5, 0.84])
	q_m, q_p = q_50-q_16, q_84-q_50
	if p!=2:
		title_fmt=".2f"
		fmt = "{{0:{0}}}".format(title_fmt).format
	else:
		title_fmt=".1f"
		fmt = "{{0:{0}}}".format(title_fmt).format
	title = r"${{{0}}}_{{-{1}}}^{{+{2}}}$"
	title = title.format(fmt(q_50), fmt(q_m), fmt(q_p))
	title = "{0} = {1}".format(tlabels[p], title)
	tlabels_final.append(title)

fig=corner_new(samples,color='k',labels=tlabels,title_hist=tlabels_final,truths=true_val,top_ticks=False,quantiles=(0.16, 0.84),show_titles=True,title_fmt=None,truth_color='b',max_n_ticks=5,plot_density=True,title_kwargs={"fontsize": 20}, label_kwargs={"fontsize": 25, "labelpad": 26},levels =level_cont, hist_kwargs = {'lw': 2},contour_kwargs= {'colors': 'red'})

Hopefully, it will useful

**Comment by csnap001** [comment]
That's great! Thank you! I'm glad you were able to find a solution

**Comment by sebitaastro** [comment]
Very useful, Thomas! Greetings from Chile.

**Comment by tdejaeger** [comment]
Con placer Sebastian!! Espero que todo va bien en Chile, personalmente despues de vivir en Berkeley y Hawaii iremos vivir en Paris ;-). Fuertes abrazos
