### ISSUE TITLE
"reverse" keyword missing in the pip release (2.0.1) and "labelpad" option request.

### ISSUE THREAD

**Issue by 3fon3fonov** [dfm/corner.py#134]
I understand that the "reverse" keyword is intrinsic to the 2.0.2 dev version, which is still not pushed to the PyPI.

However, I would like to friendly request an official release of 2.0.2, since my tools depend on the pip corner.py. I find the reverse option super useful (one can fill the empty, top-right of the cornerplot with another "reversed" cornerplot).

In addition, can you please advise on how to increase the "label pad" (spacing between values and axis labels)?

Thanks!
Trifon

**Comment by dfm** [comment]
Good call about the release - I'll try to push a new release today!

As for label padding, it's currently hard coded, I think. It shouldn't be too hard to add an option and I've certainly been in situations where I wanted to change it.

**Comment by dfm** [comment]
Actually: it looks like #119 might do what you want for the padding!

**Comment by 3fon3fonov** [comment]
Thank you for the prompt upcoming release! Both the "reverse" keyword and the #119 pull request will be great additions to the corner.py!

Please, feel free to close this issue after the new PyPi release.

Trifon

**Comment by dfm** [comment]
ok - it's live now.

```bash
python -m pip install -U corner
```

should do the trick!
