### ISSUE TITLE
Import error (No module named 'corner.corner_version')

### ISSUE THREAD

**Issue by phkphu002** [dfm/corner.py#136]
In [1]: import corner                                                                                                              
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-04a9e655f421> in <module>
----> 1 import corner

~/Library/Python/3.7/lib/python/site-packages/corner-0.0.0-py3.7.egg/corner/__init__.py in <module>
      4 
      5 from .corner import corner, hist2d, quantile
----> 6 from .corner_version import __version__  # noqa
      7 
      8 __author__ = "Dan Foreman-Mackey"

ModuleNotFoundError: No module named 'corner.corner_version'

#------------------------------------
Installed corner via pip (also tried 'conda') and still getting the same error. This installation is done on a macOS Mojave (10.14.6). Not sure what am missing here, any help in solving my problem will be highly appreciated. What worries me is that I have used corner before (months ago) in the current OS system, but recently I had to install it again, as a result facing this kind of error.

**Comment by dfm** [comment]
Are you *sure* that you didn't try to install from GitHub? That's what it looks like.. there's no corner version 0.0.0 on PyPI!

Try running:

```bash
python -m pip uninstall corner
```

a few times. Then,

```bash
python -m pip install corner
```

**Comment by phkphu002** [comment]
@dfm 
Yes, you are correct I installed from GitHub (bad move). 

the steps provided worked like magic. Thanks

**Comment by dfm** [comment]
Great - glad to hear it!
