### ISSUE TITLE
How can you set transparency ("alpha") or change the number of data points plotted ?

### ISSUE THREAD

**Issue by mdzrod** [dfm/corner.py#143]
I have a lot of data points behind my contour and would like to either change the transparency or plot less points.

**Comment by dfm** [comment]
I think you should be able to do this using:

```python
corner.corner(..., data_kwargs=dict(alpha=0.1))
```

[The default value](https://github.com/dfm/corner.py/blob/7174b5fdfd09fe79dcd1df746b457d2fabf43624/src/corner/corner.py#L786) is 0.1.

**Comment by mdzrod** [comment]
Thank you. That worked.
