### ISSUE TITLE
Installation without hdf5

### ISSUE THREAD

**Issue by JohannesBuchner** [dfm/corner.py#149]
The latest corner depends on pandas and arviz, xarray and netCDF4. Is there a more lightweight pip install option that does not include arviz/hdf5?

I am asking because my CI stopped working with this netcdf4 problem https://stackoverflow.com/questions/28931204/hdf5-headers-missing-in-installation-of-netcdf4-module-for-python .

**Comment by dfm** [comment]
@JohannesBuchner: good question! I think these are required dependencies for arviz and I'd love to keep arviz as a required dependency for corner in the long term, but perhaps it was a bit agressive to make it immediately required. It would probably be possible to make it optional until version `3.0`. For now, your best bet is probably pinning the version `<2.2` and I'll revisit this when I have a minute?

**Comment by dfm** [comment]
Also: might be worth opening or commenting on an issue on the arviz repo since they have many more users and developers!

**Comment by dfm** [comment]
v2.2.1 will be on PyPI shortly and it makes ArviZ an optional dependency. Let me know if you continue to have issues.

**Comment by JohannesBuchner** [comment]
Thank you, Dan.
