### ISSUE TITLE
Be sane about axis limits when over-plotting

### ISSUE THREAD

**Issue by dfm** [dfm/corner.py#15]
Right now, it hard sets the limits to the range of the _last_ set of samples that are plotted. This isn't very useful. You can hack this by using the `extent` keyword but it would probably be good to default to something better... like only letting the limits get bigger. Eh? :maple_leaf:

**Comment by drphilmarshall** [comment]
I think that's right: manually assigning limits is the only sane thing to
do when overplotting.

**Comment by ljschumacher** [comment]
how do I set the limits for a corner plot? I can't find it in the documentation.

**Comment by jtlz2** [comment]
@ljschumacher @dfm Any adivce on how to set limits (also can't find it in the docs)?

**Comment by ljschumacher** [comment]
Just checked my code and here is what I did
`fig = corner.corner(posterior_samples,
                        labels=["0","1","2","3","4","5","6","7","8",
                                "9","10","11","12","13","14","15"])
    # Set the x-axes of plots to be the same – the indexing is ugly and could be done better
    maxrate = np.round(np.max(np.max(posterior_samples, axis=0)))

    for rowi in range(ndim):
        for coli in range(ndim):
            if rowi == coli:
                fig.axes[rowi*ndim+coli].set_xlim(0, maxrate)`

**Comment by dfm** [comment]
@jtlz2: I believe that the issue discussed here has been fixed for several releases so can you be clearer about what you mean by "limits" here? If there is a bug, please open a new issue.

**Comment by jtlz2** [comment]
@dfm  - Fair point - I will open a new issue now :)
