### ISSUE TITLE
dependency on arviz removes python2.7 support

### ISSUE THREAD

**Issue by ahnitz** [dfm/corner.py#150]
The recent dependency addition on arviz has removed python2.7 support (and anythign < 3.6). This may (likely) have been intentional. The issue is rather that the last release was not marked as requiring python3 and is thus presented to python2.7 installations as the latest version to install before failing. 

i.e. I believe the 'python_requires' fields may need to be populated to make sure that future releases are not given as options to python2.7 legacy installations. 

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires. 

The primary problem is that the last release breaks downstream python2.7 environments. If the intention is to fully drop python2.7 support, that is understandable, however, may I request that the prior release be replaced in favor of a minor release with an updated python_requires?

**Comment by dfm** [comment]
Absolutely! I'd be happy to review a PR or I can do this later this week.

**Comment by dfm** [comment]
Should be on PyPI shortly - let me know if you run into more issues!

**Comment by ahnitz** [comment]
@dfm I think to avoid 27 installations from picking up 2.2.0, the previous 2.2.0 version may have to be taken down from pypi. The patch was merely to avoid the issue for future releases.

**Comment by dfm** [comment]
I don't understand why 2.2.0 should be removed. If your downstream package doesn't play nice with 2.2.0 the version constraints should be easy enough. What am I missing?

**Comment by ahnitz** [comment]
@dfm You are right, version constrains can handle this. The only case this prevents is the use of unpinned requirements (which will currently fail on python2.7) It's mostly an issue for upstream packages (relative to me) that have unpinned requirements. I can address that issue there however and ask that they impose a maximum corner requirement (for python2.7)

**Comment by ahnitz** [comment]
Just for clarification downstream packages need to add the following to ensure corner is installable in python2.7, otherwise 2.2.0 will still be attempted to install. I will make this suggestion to a couple downstream packages. 
```
install_requires = ['corner<=2.1.0; python_version < "2.7"']
```

**Comment by dfm** [comment]
Ah good! That makes a lot of sense. Thanks for the info. I'll remove the broken version shortly.

**Comment by dfm** [comment]
v2.2.0 has been "yanked" which means folks can install it if necessary but the installer will ignore it by default. Thanks for this!
