### ISSUE TITLE
Smooth Gaussians in corner plot

### ISSUE THREAD

**Issue by shikharmittal04** [dfm/corner.py#158]
How to get smooth Gaussians in corner plot? The option `smooth=True` did not help. Have I used the option incorrectly? The following is my code (which is the example from [here](https://emcee.readthedocs.io/en/stable/tutorials/quickstart/)). In the plot, only the contour lines are smoothened but not the Gaussian or the shaded region within the contours (which appear like squares). I have also, attached the plots with and without the `smooth=True` option. 

Thanks in advance.

```import numpy as np
import matplotlib.pyplot as plt
import tqdm

np.random.seed(123)

m_true = -0.9594
b_true = 4.294
f_true = 0.534

N = 50
x = np.sort(10 * np.random.rand(N))
yerr = 0.1 + 0.5 * np.random.rand(N)
y = m_true * x + b_true
y += np.abs(f_true * y) * np.random.randn(N)
y += yerr * np.random.randn(N)

x0 = np.linspace(0, 10, 500)

def log_likelihood(theta):
    m, b, log_f = theta
    model = m * x + b
    sigma2 = yerr ** 2 + model ** 2 * np.exp(2 * log_f)
    return -0.5 * np.sum((y - model) ** 2 / sigma2 + np.log(sigma2))

def log_prior(theta):
    m, b, log_f = theta
    if -5.0 < m < 0.5 and 0.0 < b < 10.0 and -10.0 < log_f < 1.0:
        return 0.0
    return -np.inf

m1=np.array([-1.2,-1.05,-0.9])
b1=np.array([4.2,4.8,5.4])
logf1=np.array([-1,-0.75,-0.5])

para_spc=np.array([m1,b1,logf1])
def log_probability(theta):
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + log_likelihood(theta)

import emcee

pos = np.array([-1, 4.52, -0.79]) + 1e-4 * np.random.randn(32, 3)
nwalkers, ndim = pos.shape

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_probability)
sampler.run_mcmc(pos, 1000, progress=True);

fig, axes = plt.subplots(3, figsize=(10, 7), sharex=True)
samples = sampler.get_chain()
labels = ["$m$", "$b$", "$\log f$"]

for i in range(ndim):
    ax = axes[i]
    ax.plot(samples[:, :, i], "k", alpha=0.3)
    ax.set_xlim(0, len(samples))
    ax.set_ylabel(labels[i])
    ax.yaxis.set_label_coords(-0.1, 0.5)

axes[-1].set_xlabel("step number");

settings=dict(fontsize=18)
import corner
flat_samples = sampler.get_chain(discard=100, thin=15, flat=True)
fig = corner.corner(
    flat_samples,labels=labels, truths=[m_true, b_true, np.log(f_true)],labelpad=0.01,label_kwargs=settings, smooth=True)

axes = np.array(fig.axes).reshape((ndim, ndim))

plt.show()
```

![No_smooth](https://user-images.githubusercontent.com/60473059/112708901-0488fa80-8edb-11eb-802f-19cdc4b07e03.png)
![Figure_2](https://user-images.githubusercontent.com/60473059/112708903-0652be00-8edb-11eb-89fe-fda48afa05a6.png)

**Comment by dfm** [comment]
You can smooth the 1D histograms using the `smooth_1d` parameter (I agree that the docstring is a little ambiguous): https://corner.readthedocs.io/en/latest/api.html#corner.corner

The shading is performing as expected. The size of the "pixels" are set by the `bins` parameter.

**Comment by shikharmittal04** [comment]
Thanks for the reply.  Increasing the number of `bins` solved the shading problem, but I still could not obtain smooth Gaussians. I set both the options, `smooth=True` and `smooth_1d=True`, but it's not working. In fact, there was no change on setting `smooth_1d=True`. Is it not possible to obtain a smooth plot like [this](https://www.mdpi.com/entropy/entropy-19-00327/article_deploy/html/images/entropy-19-00327-g003.png)?

**Comment by dfm** [comment]
As described in the documentation linked above, these parameters are not booleans; the should be floats. Try adjusting those parameters to get what you want.

**Comment by shikharmittal04** [comment]
Sorry, but this did not work either. I tried something like
`smooth=10.0, smooth_1d=10.0`
but the histogram is still step-like.

**Comment by dfm** [comment]
Oh - I see what you're looking for now! No, there's no KDE option. These parameters smooth out sampling noise but you're always going to see a histogram with bin sizes set by the bins parameter. If you want something different, you'll need to plot it manually using matplotlib directly. To do that, you can use the method described here to access the axis objects directly and then plot whatever you want: https://corner.readthedocs.io/en/latest/pages/custom.html

Unfortunately I can't give you more concrete suggestions.

**Comment by shikharmittal04** [comment]
Thanks.
