### ISSUE TITLE
Countours and coloring

### ISSUE THREAD

**Issue by jpmvferreira** [dfm/corner.py#164]
I'm relatively new to statistical analysis, at least of this kind, and I got redirected here by using the guide to estimate the parameters of a linear regression given noisy data given by the emcee package.

My goal was to plot something like this:
![image](https://user-images.githubusercontent.com/41581666/117543617-8198ab00-b015-11eb-83e0-b83fcfcf6c05.png)
Which was taken from the GetDist documentation.

Is this currently possible with corner? 
I would also like that the one dimensional distribution on the corners would have colors based on where the 65% and 95% levels are, which isn't plotted in the previous image, is this also possible?

I've seen issue #91 which raises issues with the 2σ plotting, has this been fixed?

Thanks in advance.

**Comment by dfm** [comment]
I'm not sure what you're asking for. If you want exactly that plot, why not use GetDist? If not, please provide a more specific question or description of your bug.

#91 is not something that will be "fixed". There is currently no planned support for more flexible titles - just make your own titles!

**Comment by dfm** [comment]
You can skip plotting the points by setting `plot_datapoints=False` and you can set the colors using `color="..."`. You can use the `smooth` and `smooth_1d` parameters to smooth over sampling noise. I'd recommend experimenting with the options listed [on the API docs](https://corner.readthedocs.io/en/latest/api.html). But, again, if you want *exactly* that plot, you should probably use a different tool!

**Comment by jpmvferreira** [comment]
Yes you are probably right, the reason I insisted was because the docs hinted at that possibility, but I just wasn't able to do so, I'll keep trying, thanks!

**Comment by dfm** [comment]
@jpmvferreira: 👍 sounds good. Drop me an email with more details if you really can't work out what you need!
