### ISSUE TITLE
Feature request: silent keyword for suppressing "too few points to create valid contours" warning

### ISSUE THREAD

**Issue by PS-OnGit** [dfm/corner.py#180]
Greetings,
Since I am using your package in a program, I noticed, that the error/warning: "_too few points to create valid contours_" spams my output, if there is a too small data input (I guess).
it would be quite nice to have an option to silence this output with a small keyword.

Kind regards,
Paul

**Comment by dfm** [comment]
It exists already! Check out the `quiet` parameter (and set it to `True`).
