### ISSUE TITLE
module 'corner' has no attribute 'corner'

### ISSUE THREAD

**Issue by FluidTop3** [dfm/corner.py#192]
I am having trouble getting corner to run. 

I've instaled it using:
`python -m pip install corner`

I am trying to run the code from the getting started section of the docs page. 

I've tried importing as: 

`from corner import corner` or
`import corner as cor` 

I keep getting the error:

`AttributeError: module 'corner' has no attribute 'corner'`

Any help would be much appreciated.

**Comment by dfm** [comment]
I can't reproduce this - there's probably an issue with your environment. I'd recommend trying to uninstall corner a few times then reinstall. Otherwise, see if you can reproduce in a clean environment. If you can, please provide exactly the steps that you used to get this issue.

**Comment by FluidTop3** [comment]
I tried running `python -m pip install corner` on my work computer and I had the same result (both are macs). 

I could not get the demo code to work until i opened a new virtual environment with absolutely nothing else installed in it. Currently corner is working for me in this environment but I am concerned that when I install other packages here that it will break again. Will keep you posted if you want.
