### ISSUE TITLE
Documentation errantly suggests labels are inferred from pandas.DataFrame columns

### ISSUE THREAD

**Issue by zachjweiner** [dfm/corner.py#217]
... in the API docs [here](https://github.com/dfm/corner.py/blob/main/src/corner/corner.py#L123-L124). 

Aside, I would personally advocate for restoring the try/except attempt to query `xs.columns`, since it requires no dependency on pandas, but merely deleting this line from the docs is an acceptable resolution, of course.

**Comment by dfm** [comment]
The docs are correct and this feature is tested here:

https://github.com/dfm/corner.py/blob/e65dd4cdeb7a9f7f75cbcecb4f07a07de65e2cea/tests/test_corner.py#L254

If you think there's a bug please feel free to include example code that demonstrates the issue.

**Comment by zachjweiner** [comment]
Sorry! I got the impression that the removal was intentional (e.g. [this warning](https://github.com/dfm/corner.py/blob/6e61b952588cf8ef1c4600bc567f14133512247b/src/corner/arviz_corner.py#L93)) and just figured the line in the docs was missed.

I should clarify that I do not have `arviz` installed. I think the issue is that [this check](https://github.com/dfm/corner.py/blob/main/src/corner/corner.py#L222-L225) passes for `pd.DataFrame` input (sanity checked this locally on main), so the import error is not raised and `corner_impl` is invoked. It's in there that I noticed the columns query was missing (but it does look like `arviz_corner` would use the column names).

For copy-pasting convenience:

```python
import numpy as np
import corner
import pandas as pd
df = pd.DataFrame(data=np.random.rand(1000, 3), columns=["x", "y", "z"])
fig = corner.corner(df)
```

![image](https://user-images.githubusercontent.com/19390728/205450797-18292996-3c20-40ae-a935-18af8127c5c6.png)

Perhaps the tests always have `arviz` installed? (Running `_run_corner(pandas=True)` locally also misses the column names.)

**Comment by dfm** [comment]
Great - thank you! This helps a lot and should be fixed. I think my preference would be to update the docs to specify that ArviZ must be installed for this to work, but I think it might also not be too hard to support pandas better until the next major release. If you're interested, I'd be happy to review a PR in either direction!

**Comment by zachjweiner** [comment]
I also lean toward simply amending the docs, since the support is deprecated anyway - and the restored support for this edge case probably would itself require a release to hit PyPI/conda-forge (plus adding testing with ArviZ uninstalled, I suppose). Sounds like a lot more effort than a handful of users simply typing `labels=df.columns`. Submitting a PR for this - if you change your mind, I'm happy to fix up the pandas support instead.
