### ISSUE TITLE
title_quantiles not working?

### ISSUE THREAD

**Issue by andresgur** [dfm/corner.py#233]
Hi, I'm trying to create a corner plot with the 1D histograms showing the 90% confidence interval instead of the usual 1sigma (68%). However, while I can see the dashed lines differing from the 68% case (i.e. responding correctly to the quantile argument) the titles remain the same. The docs say:

title_quantiles (iterable) – A list of 3 fractional quantiles to show as the the upper and lower errors. If None (default), inherit the values from quantiles, unless quantiles is None, in which case it defaults to [0.16,0.5,0.84]

But even if I explicitly supply the quantiles to title_quantiles, I get the same behaviour (i.e. the titles still show the 1 sigma conf instead). The verbose prints the correct values on the terminal though.

```
    quantiles = [0.05, 0.5, 0.95]
    corner.corner(samples_array.T, fig=fig, title_quantiles=quantiles, quantiles=quantiles,
                    show_titles=True, verbose=True,
                title_kwargs={"fontsize": 18}, labels=param_labels, max_n_ticks=3,
                 levels=(1 - np.exp(-0.5), 1 - np.exp(-0.5 * 2 ** 2)), labelpad=0.15)
```

It feels to me that the code (core.py) is not doing what is supposed to do:
```

        if show_titles:
            title = None
            if title_fmt is not None:
                # Compute the quantiles for the title. This might redo
                # unneeded computation but who cares.
                q_16, q_50, q_84 = quantile(
                    x, [0.16, 0.5, 0.84], weights=weights
                )
                q_m, q_p = q_50 - q_16, q_84 - q_50

                # Format the quantile display.
                fmt = "{{0:{0}}}".format(title_fmt).format
                title = r"${{{0}}}_{{-{1}}}^{{+{2}}}$"
                title = title.format(fmt(q_50), fmt(q_m), fmt(q_p))
```
Or else could you please let me know what am I missing?

**Comment by dfm** [comment]
Looks like you're using an older version of corner! If you take a look at the current source you'll see that things look a little different:

https://github.com/dfm/corner.py/blob/e260dad7cbfcd6c8df234a43eac007d75c1ffa8f/src/corner/core.py#L253-L270

Try updating and give it another shot.

**Comment by andresgur** [comment]
oooh my bad! Thank you so much, working now!
