### ISSUE TITLE
labelpad pushes the labels out of the figure entirely

### ISSUE THREAD

**Issue by melissa-hobson** [dfm/corner.py#262]
I'm making a cornerplot where some of my variables are very small or big (order of ~0.00001 or 10000), so the tick labels are quite long. As a result, the default settings have my tick labels overlapping my axis labels, so I'm trying to use the "labelpad" keyword of cornerplot to move the axis labels further away. However, the figure isn't resizing to accommodate these shifted labels, so effectively all I'm accomplishing is pushing my labels out of the plot entirely! Is there a way to fix this?

**Comment by dfm** [comment]
If you're saving the to a file (vs. using it in a notebook or something) then you should be able to do something like:

```python
fig = corner.corner(..., labelpad=...)
fig.savefig("corner.pdf", ..., bbox_inches="tight")
```

in order to render the full figure including labels. Let me know if that does the trick!

**Comment by melissa-hobson** [comment]
That's worked, thank you so much!
