### ISSUE TITLE
ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f')) misbehaviour. 

### ISSUE THREAD

**Issue by LydiaMak** [dfm/corner.py#276]
Hi,

I am trying to change the format of the tick labels using 

```
for ax in figure.get_axes():
    ax.tick_params(axis='both', labelsize=10)
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    ax.xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
```
 but although xaxis works OK for yaxis it shows the y labels in the middle panels as well.

<img width="225" alt="example" src="https://github.com/user-attachments/assets/bda63f27-8918-4522-8a28-669df5b62a25">

**Comment by dfm** [comment]
You'll probably need to just index over the axes around the edges. You might want to do something like:

```python
axes = np.array(figure.get_axes()).reshape((ndim, ndim))
for ax in axes[-1, :]:
  ax.xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
for ax in axes[:, 0]:
  ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
```
