### ISSUE TITLE
repeated visualization in IPython notebook

### ISSUE THREAD

**Issue by DougBurke** [dfm/corner.py#48]
In ipython notebook 3 (I forget the exact version), calling `triangle.corner` *without* capturing the return value creates two versions of the plot. I have an example of this at http://nbviewer.ipython.org/gist/DougBurke/a13dda72ca41d0a05e7d where the `Out [7]` cell shows the plot twice. I show a workaround in cell 10.

**Comment by dfm** [comment]
This happens because the corner function returns the Figure object in case you want to over plot or otherwise use the figure before saving. This will be the case in all versions of IPython, I think! Do you have a suggestion for a documentation or implementation change?

**Comment by DougBurke** [comment]
Sorry for the delay in answering. I'm not an expert in how matplotlib and the ipython notebooks interact, so I'm not necessarily the best person to come up with sensible ideas here ;-)

**Comment by zblz** [comment]
A way to avoid double plotting in notebooks is to capture the returned figure into a variable:
```
fig = corner.corner(chain)
```
