### ISSUE TITLE
Filled contours are broken in matplotlib 1.5

### ISSUE THREAD

**Issue by dfm** [dfm/corner.py#65]
This isn't what is supposed to happen!!

![hist2d_filled](https://cloud.githubusercontent.com/assets/350282/11180601/e4a081c8-8c53-11e5-9590-2d51ae912b87.png)

**Comment by dfm** [comment]
Thanks for this! I don't think that it'll be quite as easy as sorting... we want the "each level to infinity" style from your link not the "increasing levels" style. But I'm sure it won't be hard to fix based on this! I'll try to do it later today. Thanks again!

**Comment by tacaswell** [comment]
Are you using the 'each level to infinity' to get the alpha blending?  If that is the case, it would be easier to use a color map which has alpha in some of the values and an increasing set of levels.

**Comment by dfm** [comment]
@tacaswell: I'm sure there must be a better way! Here's the current (hackish/embarrassing) implementation that I wrote years ago. Any suggestions you have would be much appreciated.

https://github.com/dfm/corner.py/blob/master/corner.py#L479
